# -- Markup --
# These settings are required for Congo theme to function.
goldmark:
  renderer:
    unsafe: true
highlight:
  noClasses: false
  anchorLineNos: true
  codeFences: true
  guessSyntax: true
tableOfContents:
  startLevel: 2
  endLevel: 4