# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.
main:
  - identifier: posts
    name: 博客
    pageRef: /posts/
    weight: 1
  - identifier: categories
    name: 分类
    pageRef: categories
    weight: 2
  - identifier: about
    name: 关于我
    pageRef: /about
    weight: 3
  - identifier: search
    weight: 4
    params:
      action: search
      icon: search

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
footer:
  - name: Island 岛屿
    url: https://mast.dragon-fly.club
    weight: 1
    title: Island 岛屿
    params:
      target: _blank
  - name: DragonCraft
    url: https://minecraft.dragon-fly.club/?utm_source=holger-blog&utm_medium=footer
    weight: 2
    title: DragonCraft
    params:
      target: _blank
  - name: 天津外国语大学附属外国语学校(镜像)
    url: https://tfls.online/?utm_source=holger-blog&utm_medium=footer
    weight: 3
    title: 天津外国语大学附属外国语学校(镜像)
    params:
      target: _blank
