# This file is dedicated to theme configurations

# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme: sapphire
defaultAppearance: light # valid options: light or dark
autoSwitchAppearance: true
enableSearch: true
enableCodeCopy: true
enableImageLazyLoading: true
enableImageWebp: false
fingerprintAlgorithm: sha256
enableQuicklink: true
header:
  layout: hybrid 
  # logo: images/logo.png
  # logoDark: images/logo-dark.png
  showTitle: true
footer:
  showCopyright: true
  showThemeAttribution: false
  showAppearanceSwitcher: true
  showScrollToTop: true
homepage:
  layout: profile
  showRecent: true
  recentLimit: 5
article:
  showDate: true
  showDateUpdated: true
  showAuthor: true
  showBreadcrumbs: true
  showDraftLabel: true
  showEdit: true
  editURL: https://code.dragoncloud.win/holgerhuo/blog/src/branch/main/content
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: true
  showWordCount: true
  showComments: true
list:
  showBreadcrumbs: false
  showSummary: true
  showTableOfContents: true
  showTaxonomies: true
  groupByYear: true
  paginationWidth: 1
sitemap:
  excludedKinds:
    - taxonomy
    - term
taxonomy:
  showTermCount: true
plausibleAnalytics:
  domain: holger.one
  event: https://report.dragoncloud.win/api/event
  script: https://report.dragoncloud.win/js/script.outbound-links.file-downloads.tagged-events.js
